services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vr-ticket-for-whatsapp
    restart: always
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.http.routers.vr-ticket.entrypoints: websecure
      traefik.http.routers.vr-ticket.rule: Host(`vr-ticket.lucascriado.com`)
      traefik.http.routers.vr-ticket.tls.certresolver: letsencrypt
      traefik.http.services.vr-ticket.loadbalancer.server.port: "3000"
